spring.application.name=AutoDocs

# Ativa o console do H2
spring.h2.console.enabled=true

# Define um caminho fixo (opcional, mas ajuda)
spring.h2.console.path=/h2-console

# Garante que o banco em memória não suma toda hora
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=